#!/usr/bin/env bash

# run the python scripts to calculate the polynomial mapping for the year ranges for
# both the HadISST and CMIP5 component of the long runs

MAX_DEG=$1

BASE_DIR=/Users/Neil/Coding/CREDIBLE_output/output

for ((yr1=1899;yr1<=1989;yr1+=10));
do
    yr2=$(($yr1+11))
    C_DIR=$BASE_DIR"/HadISST_"$yr1"_"$yr2
    F_NAME=$C_DIR/"hadisst_polyfit_"$yr1"_"$yr2"_"$MAX_DEG"_400_anoms.nc"
#    mv $F_NAME ${F_NAME/".nc"/"_sm.nc"}
done

yr1=2006
yr2=2010

C_DIR=$BASE_DIR"/rcp45_"$yr1"_"$yr2
F_NAME=$C_DIR/"cmip5_polyfit_rcp45_"$yr1"_"$yr2"_"$MAX_DEG"_anoms.nc"
mv $F_NAME ${F_NAME/".nc"/"_sm.nc"}

for ((yr1=2009;yr1<2090;yr1+=10));
do
    yr2=$(($yr1+11))

    C_DIR=$BASE_DIR"/rcp45_"$yr1"_"$yr2
    F_NAME=$C_DIR/"cmip5_polyfit_rcp45_"$yr1"_"$yr2"_"$MAX_DEG"_anoms.nc"
    mv $F_NAME ${F_NAME/".nc"/"_sm.nc"}

done